"""add_designation_department_to_company_members_and_invitations

Revision ID: 0f180573f272
Revises: 7598449ac1d4
Create Date: 2026-08-24 14:50:48.996622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f180573f272'
down_revision: Union[str, Sequence[str], None] = '7598449ac1d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_invitations', sa.Column('designation', sa.String(length=100), nullable=True))
    op.add_column('company_invitations', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('company_members', sa.Column('designation', sa.String(length=100), nullable=True))
    op.add_column('company_members', sa.Column('department', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_members', 'department')
    op.drop_column('company_members', 'designation')
    op.drop_column('company_invitations', 'department')
    op.drop_column('company_invitations', 'designation')
    # ### end Alembic commands ###
