"""add_team_visuals_archiving_and_activity

Revision ID: 4c57821cc4ef
Revises: 1ced057bf49a
Create Date: 2026-08-24 21:48:15.293839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c57821cc4ef'
down_revision: Union[str, Sequence[str], None] = '1ced057bf49a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_activities_action'), 'team_activities', ['action'], unique=False)
    op.create_index(op.f('ix_team_activities_actor_user_id'), 'team_activities', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_team_activities_team_id'), 'team_activities', ['team_id'], unique=False)
    op.add_column('teams', sa.Column('icon', sa.String(length=50), nullable=True))
    op.add_column('teams', sa.Column('color', sa.String(length=50), nullable=True))
    op.add_column('teams', sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_teams_is_archived'), 'teams', ['is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_is_archived'), table_name='teams')
    op.drop_column('teams', 'is_archived')
    op.drop_column('teams', 'color')
    op.drop_column('teams', 'icon')
    op.drop_index(op.f('ix_team_activities_team_id'), table_name='team_activities')
    op.drop_index(op.f('ix_team_activities_actor_user_id'), table_name='team_activities')
    op.drop_index(op.f('ix_team_activities_action'), table_name='team_activities')
    op.drop_table('team_activities')
    # ### end Alembic commands ###
