"""add_company_profile_fields

Revision ID: c32434664e1b
Revises: 364dbd7da92c
Create Date: 2026-08-24 10:35:14.188533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c32434664e1b'
down_revision: Union[str, Sequence[str], None] = '364dbd7da92c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('company_size', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'logo_url')
    op.drop_column('companies', 'website')
    op.drop_column('companies', 'city')
    op.drop_column('companies', 'country')
    op.drop_column('companies', 'company_size')
    op.drop_column('companies', 'industry')
    # ### end Alembic commands ###
